repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      # - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=1500"]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        args: [
          # E501 let black handle all line length decisions
          # W503 black conflicts with "line break before operator" rule
          # E203 black conflicts with "whitespace before ':'" rule
          # E231 black conflicts with "Whitspace after ':'" rule

          '--ignore=E501,W503,E203,C901,E231' ]